version: 2

build:
  image: "ubuntu-20.04"
  tools:
    python: "3.8"
    pip: "20.3"
    conda: "4.10.3"

python:
  version: "3.8"
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py
